### PR TITLE
Added a java implementation

### PR DESCRIPTION
**Pull request by mattonerampeo**
The implementation is pretty fast.
I also added a tests directory as I find it useful.

### CODE REVIEW

**Comment by mattonerampeo** [comment]
I should add that I tried to follow OOP principles as much as possible.
The code is pretty organized and I tried to make everything as self explanatory as possible.
Hope this is good enough to get approved, since no optimizations are in place.

**Review by TheTipo01 — APPROVED** [review]
You could've kept track of the brackets and then matched them, but whatever.

**Comment by mattonerampeo** [comment]
I mean, sure. But the performance is already comparable to other interpreters we support. I think this is a good enough starting point for a java library useful for interpretation.
I'm going to start making some improvements for later, but I think we should consider merging this as of now.

**Comment by NotHexadecimal** [comment]
Yeah, optimizations can always be added later, for now it's more than good enough.

**Review by NotHexadecimal — APPROVED** [review]

**Comment by NotHexadecimal** [comment]
Note: the test folder will eventually be moved into a folder common to all interpreters.

**Pull request merged**
